# Generated by Django 3.1.2 on 2020-10-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoredDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=200)),
                ('dish_type', models.CharField(max_length=20)),
                ('ingredient', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
            ],
        ),
    ]
