# Generated by Django 3.1.2 on 2020-10-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealmageapp', '0005_storeddish_meal_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryList',
        ),
        migrations.AddField(
            model_name='storeddish',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storeddish',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeddish',
            name='dish_type',
            field=models.CharField(max_length=20),
        ),
    ]
