# Generated by Django 3.1.2 on 2020-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmageapp', '0007_grocerylist_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeddish',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('italian', 'Italian'), ('korean', 'Korean'), ('indian', 'Indian'), ('ethiopian', 'Ethiopian'), ('vietnamese', 'Vietnamese'), ('thai', 'Thai'), ('sushi', 'Sushi'), ('panasian', 'Pan Asian'), ('mexican', 'Mexican'), ('german', 'German'), ('japanese', 'Japanese'), ('cajun', 'Cajun'), ('texmex', 'Texmex'), ('greek', 'Greek'), ('mediterranean', 'Mediterranean'), ('french', 'French'), ('southern', 'Southern'), ('spanish', 'Spanish'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='storeddish',
            name='dish_type',
            field=models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storeddish',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20),
        ),
    ]
