# Generated by Django 3.1.2 on 2020-11-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmageapp', '0009_auto_20201104_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeddish',
            name='ingredient16',
        ),
    ]
