# Generated by Django 3.1.2 on 2020-11-24 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mealmageapp', '0010_remove_storeddish_ingredient16'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_dish_entree', models.CharField(blank=True, max_length=200)),
                ('breakfast_dish_side_1', models.CharField(blank=True, max_length=200)),
                ('breakfast_dish_side_2', models.CharField(blank=True, max_length=200)),
                ('breakfast_dish_side_3', models.CharField(blank=True, max_length=200)),
                ('lunch_dish_entree', models.CharField(blank=True, max_length=200)),
                ('lunch_dish_side_1', models.CharField(blank=True, max_length=200)),
                ('lunch_dish_side_2', models.CharField(blank=True, max_length=200)),
                ('lunch_dish_side_3', models.CharField(blank=True, max_length=200)),
                ('dinner_dish_entree', models.CharField(blank=True, max_length=200)),
                ('dinner_dish_side_1', models.CharField(blank=True, max_length=200)),
                ('dinner_dish_side_2', models.CharField(blank=True, max_length=200)),
                ('dinner_dish_side_3', models.CharField(blank=True, max_length=200)),
                ('dessert_dish', models.CharField(blank=True, max_length=200)),
                ('snack_dish_1', models.CharField(blank=True, max_length=200)),
                ('snack_dish_2', models.CharField(blank=True, max_length=200)),
                ('snack_dish_3', models.CharField(blank=True, max_length=200)),
                ('meal_plan_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
