# Generated by Django 3.2.1 on 2021-06-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmageapp', '0012_auto_20201128_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenu',
            options={'verbose_name_plural': 'Daily Menus'},
        ),
        migrations.RenameField(
            model_name='dailymenu',
            old_name='meal_plan_date',
            new_name='menu_date',
        ),
    ]
