# Generated by Django 3.2.1 on 2021-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmageapp', '0014_menucalendarentry_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucalendarentry',
            name='menu_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
